### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Forrest-Z** [ethz-asl/gflags_catkin#20]
Install configuration: "Release"
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/libgflags.so.2.2.1
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/libgflags.so.2.2
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/libgflags.so
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/libgflags_nothreads.so.2.2.1
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/libgflags_nothreads.so.2.2
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/libgflags_nothreads.so
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/include/gflags/gflags.h
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/include/gflags/gflags_declare.h
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/include/gflags/gflags_completions.h
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/cmake/gflags/gflags-config.cmake
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/cmake/gflags/gflags-config-version.cmake
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/cmake/gflags/gflags-targets.cmake
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/cmake/gflags/gflags-targets-release.cmake
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/bin/gflags_completions.sh
-- Up-to-date: /home/forrest/project/ros/mydt_ws/devel/lib/pkgconfig/gflags.pc
-- Installing: /home/forrest/.cmake/packages/gflags/56572a4e7d282a7931755b251e780914
CMake Error at cmake_install.cmake:151 (file):
  file INSTALL cannot copy file
  "/home/forrest/project/ros/mydt_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src/gflags-registry-entry"
  to "/home/forrest/.cmake/packages/gflags/56572a4e7d282a7931755b251e780914".

Makefile:105: recipe for target 'install' failed
make[3]: *** [install] Error 1
gflags_catkin/CMakeFiles/gflags_src.dir/build.make:73: recipe for target 'gflags_catkin/gflags_src-prefix/src/gflags_src-stamp/gflags_src-install' failed
make[2]: *** [gflags_catkin/gflags_src-prefix/src/gflags_src-stamp/gflags_src-install] Error 2
CMakeFiles/Makefile2:575: recipe for target 'gflags_catkin/CMakeFiles/gflags_src.dir/all' failed
make[1]: *** [gflags_catkin/CMakeFiles/gflags_src.dir/all] Error 2

**Comment by xiaoyuamw** [comment]
@Forrest-Z 
您好，
请问一下这个问题您解决了吗？如果解决了，那是怎么样解决的呢？
谢谢！
