### ISSUE TITLE
Why are we using the svn to get gflags?

### ISSUE THREAD

**Issue by furgalep** [ethz-asl/gflags_catkin#5]
From what I see, the latest gflags is available through git:

https://code.google.com/p/gflags/

This is only a problem because the svn sometimes fails to respond, causing the build to fail.

I didn't switch it because it looks like the new git version uses cmake and not configure to build and this would take some wrangling to get right.

Can someone look at this? @tcies @dymczykm @simonlynen

**Comment by simonlynen** [comment]
we use git now.
